= Asciidoctor-diagram Changelog

== 1.1.6

Enhancements::

  * Updated PlantUML to revision 8000 (23/06/2014)
  * Add support for Shaape diagrams (requires Shaape to be installed separately)

== 1.1.5

Enhancements::

  * Use the output directory (outdir attribute) as base directory if it's specified.
  * Do not auto-generate width/height attributes when outputting to a non-HTML backend. This resolves issues with
    oversized images in docbook output.

== 1.1.4

Bug Fixes::

  * Under CRuby in combination with certain Java versions a FileNotFoundException could be triggered due to incorrect
    method selection by RJB

== 1.1.3

Bug Fixes::

  * Image regeneration logic did not always correctly detect cases where images did not need to be updated

== 1.1.2

Bug Fixes::

  * Fix corrupt PNG images on Windows
  * Fix NoSuchMethodError in block macro processing when target image file already existed
  * Respect target attribute in block macros

== 1.1.1

Bug Fixes::

  * Changed rjb dependency from ~> 1.4.9 to ~> 1.4.8 to be compatible with buildr 1.4.15

== 1.1.0

Enhancements::

  * Add support for `graphviz` blocks which may contain diagrams specified using the Graphviz DOT language
  * The location of the Graphviz `dot` executable can now be specified using the `graphvizdot` document attribute
  * Add support for `ditaa`, `graphivz` and `plantuml` block macros

== 1.0.1

Bug Fixes::

  * Corrections to gemspec

== 1.0.0

Initial release::

  * Provides Asciidoctor extension for `ditaa` and `plantuml` blocks
  * PlantUML skin parameters can be injected from an external file using the `plantumlconfig` document attribute