= Asciidoctor-diagram Changelog

== 1.5.0 (Not released yet)

Enhancements::

  * Issue #98: Automatically detect Actdiag, Blockdiag, Nwdiag and Seqdiag executables from Python 3.x Debian packages.
  * Issue #100: Support specifying the layout engine for `dot` (`-K<engine>`) using the `layout` attribute on `graphviz` blocks. 
  * Issue #102: Generate cache files in `asciidoctor/diagram` to avoid cluttering the output directory.
  * Issue #105: Support substitutions in diagram blocks.
  * Issue #107: Improve error reporting when Mermaid diagram generation fails.

== 1.4.0

Enhancements::

  * Use wavedrom-cli when available
  * Add meme generator

Bug Fixes::

  * Issue #71: Don't fail early for PlantUML diagrams if `dot` can't be found. PlantUML doesn't need it for all diagrams
    types so invoke PlantUML without specifying the location of `dot` and let PlantUML produce an error when necessary.
  * Issue #85: Support target attribute values containing one or more directory names.

== 1.3.2

Enhancements::

  * Add support for WaveDrom diagrams (requires WaveDrom Editor to be installed separately)
  * Allow error handling to be controlled using the `diagram-on-error` attribute.
    Setting this attribute to `log` (default) logs an error message and continues processing of the document.
    Setting it to `abort` triggers an exception and aborts document processing.
  * Resolve relative image references in PlantUML diagrams to absolute ones up front to ensure PlantUML can locate the images

Bug Fixes::

  * Issue #83: Omit stack trace information from error message that gets embedded in the output document
  * Issue #84: Restore support for specifying the location of the `dot` executable using the `graphvizdot` attribute

== 1.3.1

Bug Fixes::

  * Issue #78: Resolve Java launch issues when running in a Cygwin environment

== 1.3.0

Enhancements::

  * Introduces a documented, public extension API
  * Add support for Actdiag diagrams (requires Actdiag to be installed separately)
  * Add support for Seqdiag diagrams (requires Seqdiag to be installed separately)
  * Add support for Nwdiag diagrams (requires Nwdiag to be installed separately)
  * Add support for Salt UI diagrams (issue #66)
  * Updated PlantUML to revision 8028 (10/07/2015)
  * Remove dependency on RJB to simplify installation (issue #48)
  * Add diagram scaling support using the scale attribute (issue #58)
  * Add Ditaa command line option support using the options attribute (issue #69)

Bug Fixes::

  * Issue #49: Resolve issue that made Java 6 installation prompt appear on Mac OS X
  * Issue #51: Resolved issue where PNG files generated by Graphviz were not processed correctly on Windows

== 1.2.0

Enhancements::

  * Updated to Asciidoctor 1.5.0

== 1.1.6

Enhancements::

  * Updated PlantUML to revision 8002 (23/07/2014)
  * Add support for Shaape diagrams (requires Shaape to be installed separately)
  * Add support for Blockdiag diagrams (requires Blockdiag to be installed separately)

Bug Fixes::

  * Issue #38: Resolved Graphviz syntax errors with certain diagrams

== 1.1.5

Enhancements::

  * Use the output directory (outdir attribute) as base directory if it's specified.
  * Do not auto-generate width/height attributes when outputting to a non-HTML backend. This resolves issues with
    oversized images in docbook output.

== 1.1.4

Bug Fixes::

  * Under CRuby in combination with certain Java versions a FileNotFoundException could be triggered due to incorrect
    method selection by RJB

== 1.1.3

Bug Fixes::

  * Image regeneration logic did not always correctly detect cases where images did not need to be updated

== 1.1.2

Bug Fixes::

  * Fix corrupt PNG images on Windows
  * Fix NoSuchMethodError in block macro processing when target image file already existed
  * Respect target attribute in block macros

== 1.1.1

Bug Fixes::

  * Changed rjb dependency from ~> 1.4.9 to ~> 1.4.8 to be compatible with buildr 1.4.15

== 1.1.0

Enhancements::

  * Add support for `graphviz` blocks which may contain diagrams specified using the Graphviz DOT language
  * The location of the Graphviz `dot` executable can now be specified using the `graphvizdot` document attribute
  * Add support for `ditaa`, `graphivz` and `plantuml` block macros

== 1.0.1

Bug Fixes::

  * Corrections to gemspec

== 1.0.0

Initial release::

  * Provides Asciidoctor extension for `ditaa` and `plantuml` blocks
  * PlantUML skin parameters can be injected from an external file using the `plantumlconfig` document attribute
