= Asciidoctor Diagram
Pepijn Van_Eeckhoudt <https://github.com/pepijnve[@pepijnve]>; Sarah White <https://github.com/graphitefriction[@graphitefriction]>
:description: README for the Asciidoctor Diagram extension for Asciidoctor.
ifdef::env-github[:toc: macro]
ifndef::env-site[:toc: preamble]
ifndef::imagesdir[:imagesdir: docs/modules/ROOT/images]
:icons: font
:source-highlighter: coderay
:source-language: asciidoc
:table-caption!:
:example-caption!:
:figure-caption!:
:check: icon:check[]
ifdef::env-github[:check: :ballot_box_with_check:]
ifndef::env-site[:status:]
include::docs/modules/ROOT/partials/uris.adoc[]

Asciidoctor Diagram is a set of Asciidoctor extensions that enable you to add diagrams, which you describe using plain text, to your AsciiDoc document.

The extensions supports the {uri-a2s}[AsciiToSVG], BlockDiag ({uri-blockdiag}[BlockDiag], {uri-seqdiag}[SeqDiag], {uri-actdiag}[ActDiag], {uri-nwdiag}[NwDiag]), {uri-bytefield}[Bytefield-SVG], {uri-ditaa}[Ditaa], {uri-dpic}[dpic], {uri-erd}[Erd], {uri-gnuplot}[Gnuplot], {uri-dot}[GraphViz], {uri-mermaid}[Mermaid], {uri-mscgen}[Msc], {uri-nomnoml}[Nomnoml], {uri-pikchr}[Pikchr], {uri-plantuml}[PlantUML], {uri-shaape}[Shaape], {uri-smcat}[State Machine Cat], {uri-svgbob}[SvgBob], {uri-symbolator}[Symbolator], {uri-syntrax}[Syntrax], {uri-umlet}[UMLet], {uri-vega}[Vega], {uri-vegalite}[Vega-Lite] and {uri-wavedrom}[WaveDrom] syntax.

Each extension runs the diagram processor to generate an SVG, PNG, or TXT file from the input text.
The generated file is then inserted into your converted document.

Asciidoctor Diagram was inspired by the {uri-py-plantuml}[AsciiDoc PlantUML filter].

ifndef::env-site[]
Translations of the document are available in the following languages:

* link:README_zh-CN.adoc[汉语]
endif::[]

ifdef::status[]
[discrete]
== Status

image:https://github.com/asciidoctor/asciidoctor-diagram/workflows/Linux%20unit%20tests/badge.svg?branch=master["Linux Build Status", link="https://github.com/asciidoctor/asciidoctor-diagram/actions?query=workflow%3A%22Linux+unit+tests%22"]
image:https://ci.appveyor.com/api/projects/status/4r4gkk5gy3igs6nh/branch/master?svg=true["Windows Build Status", link="https://ci.appveyor.com/project/asciidoctor/asciidoctor-diagram"]
image:https://badge.fury.io/rb/asciidoctor-diagram.svg[Gem Version, link=https://rubygems.org/gems/asciidoctor-diagram]
endif::status[]

ifeval::["{toc-placement}" == "macro"]
[discrete]
== Contents

toc::[title={blank}]
endif::[]

include::docs/modules/ROOT/partials/installation.adoc[]
include::docs/modules/ROOT/partials/create_diagram.adoc[]
include::docs/modules/ROOT/partials/generate.adoc[]
include::docs/modules/ROOT/partials/advanced.adoc[]