require 'asciidoctor-diagram/blockdiag'
require 'asciidoctor-diagram/ditaa'
require 'asciidoctor-diagram/graphviz'
require 'asciidoctor-diagram/mermaid'
require 'asciidoctor-diagram/plantuml'
require 'asciidoctor-diagram/salt'
require 'asciidoctor-diagram/shaape'
require 'asciidoctor-diagram/wavedrom'