= Structurizr
include::partial$uris.adoc[]

{uri-structurizr}[Structurizr] builds upon "diagrams as code", allowing you to create multiple software architecture diagrams from a single model.
There are a number of tools for creating Structurizr compatible workspaces, with the Structurizr DSL being the recommended option for most teams.

The Structurizr extension allows individual views from a Structurizr DSL workspace to be included in Asciidoc documents.
This is the inverse use case of https://structurizr.com/help/documentation[Structurizr's documentation] support which lets you embed Asciidoc in the Structurizr DSL.

== Output Formats

- PNG
- SVG

== Common Attributes

include::partial$shared-attrs.adoc[]

== Structurizr Attributes

[cols=">,<,<",options="header"]
|===
|Name          |Default value   |Description
|renderer      |plantuml-c4     |The rendering backend to use. One of `d2`, `graphviz`, `mermaid`, `plantuml`, or `plantuml-c4`
|view          |unspecified     |The key of the view to render
|===