= Vega / Vega-Lite
include::partial$uris.adoc[]

{uri-vega}[Vega] and {uri-vegalite}[Vega-Lite] are declarative language for creating, saving, and sharing interactive visualization designs.

Vega provides basic building blocks for a wide variety of visualization designs: data loading and transformation, scales, map projections, axes, legends, and graphical marks such as rectangles, lines, plotting symbols, etc.

Vega-Lite provides a more concise and convenient form to author common visualizations. As Vega-Lite can compile its specifications to Vega specifications, users may use Vega-Lite as the primary visualization tool and, if needed, transition to use the lower-level Vega for advanced use cases.

== Supported Image Formats

- PNG
- SVG

== Attributes

|vega         |{uri-vega}[vg2png] and/or {uri-vega}[vg2png]                          |`vg2png` and `vg2svg`
|vegalite     |{uri-vegalite}[vl2vg] and {uri-vega}[vg2png] and/or {uri-vega}[vg2svg]|`vl2vg`, `vg2png` and `vg2svg`

[cols=">,<,<",options="header"]
|===
|Name          |Default value   |Description
|vg2png        |vg2png          |The path to the `vg2png` executable. This attribute is used for PNG output.
|vg2svg        |vg2svg          |The path to the `vg2svg` executable This attribute is used for SVG output.
|vl2vg         |vl2vg           |The path to the `vl2vg` executable. This attribute is used for Vega-Lite diagrams.
|===

None